LOCK TABLES `AB_Client` WRITE;
INSERT INTO `AB_Client` (`uuid`, `created_at`, `updated_at`, `Availability`, `Flexible Dates`, `Cross Cultural Relationship`, `Last Name`, `Primary Language`, `Emergency Email`, `Newsletter`, `First Time`, `Concerns meeting together`, `Date Birth`, `Emergency Phone`, `Emergency Contact`, `Gender`, `Occupation`, `Phone`, `Prescription Medication`, `Medical Issues`, `Email`, `Cross Cultural Service Years`, `Topics More Info`, `Topics`, `Passport Country`, `First Name`) VALUES ("02a293e6-492a-4dca-8a84-4d81da450c23", NOW(), NOW(), "Jan 1", "Yes", "Somewhat", "Green", "English", "sss@email.com", "No", "No", "No", NOW(), "11111", "sss", "Male", "IT", "998887", "No", "No:", "email@email.com", "12", "Yes details", "Career Choices, Difficult Experiences", "Cambodia", "Tim");
INSERT INTO `AB_Client` (`uuid`, `created_at`, `updated_at`, `Availability`, `Flexible Dates`, `Cross Cultural Relationship`, `Last Name`, `Primary Language`, `Emergency Email`, `Newsletter`, `First Time`, `Concerns meeting together`, `Date Birth`, `Emergency Phone`, `Emergency Contact`, `Gender`, `Occupation`, `Phone`, `Prescription Medication`, `Medical Issues`, `Email`, `Cross Cultural Service Years`, `Topics More Info`, `Topics`, `Passport Country`, `First Name`) VALUES ("d647e27d-cb0b-456a-83db-98a3e62eaf12", NOW(), NOW(), "Jan 1", "Yes", "Somewhat", "Green", "English", "sss@email.com", "No", "No", "No", NOW(), "11111", "sss", "Female", "IT", "998887", "No", "No:", "email@email.com", "12", "Yes details", "Career Choices, Difficult Experiences", "Cambodia", "Jill");
UNLOCK TABLES;
LOCK TABLES `AB_WellIntake` WRITE;
INSERT INTO `AB_WellIntake` (`uuid`, `created_at`, `updated_at`, `Timestamp`, `Provider Request`, `Service`, `Location`, `Bill to`, `Feedback`) VALUES ("b12ad108-1b47-452f-8500-fb3bfcd0359d", NOW(), NOW(), NOW(), "Any Provider", "Counseling", "Well - Chiang Mai", "Tim Green", "None");
UNLOCK TABLES;
LOCK TABLES `AB_Case` WRITE;
INSERT INTO `AB_Case` (`uuid`, `created_at`, `updated_at`, `type`, `service`) VALUES ("9ba7674a-c25e-4d16-8cb4-4f930a4fc208", NOW(), NOW(), "Individual", "Counselling");
UNLOCK TABLES;
LOCK TABLES `AB_Provider` WRITE;
INSERT INTO `AB_Provider` (`uuid`, `created_at`, `updated_at`, `First NAme`, `Last Name`) VALUES ("40a94cea-3e70-40ad-a844-9d6c136f6894", NOW(), NOW(), "Peter", "Parker");
UNLOCK TABLES;
LOCK TABLES `AB_JOINMN_Case_Provider_Provider` WRITE;
INSERT INTO `AB_JOINMN_Case_Provider_Provider` (`created_at`, `updated_at`, `id`, `Case`, `Provider`) VALUES (NOW(), NOW(), "1", "9ba7674a-c25e-4d16-8cb4-4f930a4fc208", "40a94cea-3e70-40ad-a844-9d6c136f6894");
UNLOCK TABLES;
LOCK TABLES `AB_JOINMN_Case_Client_Clients` WRITE;
INSERT INTO `AB_JOINMN_Case_Client_Clients` (`created_at`, `updated_at`, `id`, `Client`, `Case`) VALUES (NOW(), NOW(), "1", "02a293e6-492a-4dca-8a84-4d81da450c23", "9ba7674a-c25e-4d16-8cb4-4f930a4fc208");
UNLOCK TABLES;
LOCK TABLES `AB_JOINMN_Well-Intake_Client_Clients` WRITE;
INSERT INTO `AB_JOINMN_Well-Intake_Client_Clients` (`created_at`, `updated_at`, `id`, `Client`, `Well-Intake`) VALUES (NOW(), NOW(), "1", "02a293e6-492a-4dca-8a84-4d81da450c23", "b12ad108-1b47-452f-8500-fb3bfcd0359d");
INSERT INTO `AB_JOINMN_Well-Intake_Client_Clients` (`created_at`, `updated_at`, `id`, `Client`, `Well-Intake`) VALUES (NOW(), NOW(), "2", "d647e27d-cb0b-456a-83db-98a3e62eaf12", "b12ad108-1b47-452f-8500-fb3bfcd0359d");
UNLOCK TABLES;
