SET FOREIGN_KEY_CHECKS = 0;
LOCK TABLES `AB_Case` WRITE;
TRUNCATE TABLE `AB_Case`;
UNLOCK TABLES
LOCK TABLES `AB_Client` WRITE;
TRUNCATE TABLE `AB_Client`;
UNLOCK TABLES
LOCK TABLES `AB_Charges` WRITE;
TRUNCATE TABLE `AB_Charges`;
UNLOCK TABLES
LOCK TABLES `AB_Engagement` WRITE;
TRUNCATE TABLE `AB_Engagement`;
UNLOCK TABLES
LOCK TABLES `AB_Family` WRITE;
TRUNCATE TABLE `AB_Family`;
UNLOCK TABLES
LOCK TABLES `AB_Group` WRITE;
TRUNCATE TABLE `AB_Group`;
UNLOCK TABLES
LOCK TABLES `AB_MOU` WRITE;
TRUNCATE TABLE `AB_MOU`;
UNLOCK TABLES
LOCK TABLES `AB_Provider` WRITE;
TRUNCATE TABLE `AB_Provider`;
UNLOCK TABLES
LOCK TABLES `AB_ServiceHistory` WRITE;
TRUNCATE TABLE `AB_ServiceHistory`;
UNLOCK TABLES
LOCK TABLES `AB_Transaction` WRITE;
TRUNCATE TABLE `AB_Transaction`;
UNLOCK TABLES
LOCK TABLES `AB_WellEntity` WRITE;
TRUNCATE TABLE `AB_WellEntity`;
UNLOCK TABLES
LOCK TABLES `AB_WellIntake` WRITE;
TRUNCATE TABLE `AB_WellIntake`;
UNLOCK TABLES
LOCK TABLES `AB_WellReceipt` WRITE;
TRUNCATE TABLE `AB_WellReceipt`;
UNLOCK TABLES
LOCK TABLES `AB_WellRelationship` WRITE;
TRUNCATE TABLE `AB_WellRelationship`;
UNLOCK TABLES
SET FOREIGN_KEY_CHECKS = 1;
